-- MySQL initial schema for the education backend.
-- Consolidated baseline; not a translation of the SQLite migration history.
--
-- Design constraints (see docs/MYSQL_MIGRATION_PLAN.md):
--   * No foreign keys, cascades, unique constraints, CHECKs, or triggers.
--     Referential integrity, uniqueness, and cascading cleanup are enforced
--     by application code inside transactions.
--   * Only primary keys and non-unique query-performance indexes.
--   * All audit timestamps are Unix seconds (BIGINT) generated by Rust.
--   * `key` is a reserved word in MySQL and must stay backticked.

CREATE TABLE users (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    avatar VARCHAR(512) NOT NULL DEFAULT '',
    email VARCHAR(255) NULL,
    mobile VARCHAR(32) NULL,
    display_name VARCHAR(100) NOT NULL DEFAULT '',
    status TINYINT NOT NULL DEFAULT 1,
    session_epoch INT NOT NULL DEFAULT 0,
    manager_id BIGINT NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX users_manager_id ON users(manager_id);
CREATE INDEX users_created_by ON users(created_by);
CREATE INDEX users_status ON users(status);

CREATE TABLE roles (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NULL,
    data_scope VARCHAR(20) NOT NULL DEFAULT 'self',
    level INT NOT NULL DEFAULT 100,
    built_in TINYINT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX roles_code ON roles(code);
CREATE INDEX roles_status ON roles(status);

CREATE TABLE permissions (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NULL,
    module VARCHAR(50) NOT NULL DEFAULT '',
    built_in TINYINT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX permissions_code ON permissions(code);
CREATE INDEX permissions_module ON permissions(module);
CREATE INDEX permissions_status ON permissions(status);

CREATE TABLE user_roles (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at BIGINT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX user_roles_user_id ON user_roles(user_id);
CREATE INDEX user_roles_role_id ON user_roles(role_id);

CREATE TABLE role_permissions (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    created_at BIGINT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX role_permissions_role_id ON role_permissions(role_id);
CREATE INDEX role_permissions_permission_id ON role_permissions(permission_id);

CREATE TABLE auth_sessions (
    token_hash VARCHAR(64) NOT NULL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    session_epoch INT NOT NULL DEFAULT 0,
    csrf_token VARCHAR(64) NOT NULL,
    login_log_id BIGINT NULL,
    created_at BIGINT NOT NULL DEFAULT 0,
    last_seen_at BIGINT NOT NULL DEFAULT 0,
    expires_at BIGINT NOT NULL DEFAULT 0,
    client_ip VARCHAR(64) NOT NULL DEFAULT '',
    user_agent VARCHAR(512) NOT NULL DEFAULT ''
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX auth_sessions_user_id ON auth_sessions(user_id);
CREATE INDEX auth_sessions_expires_at ON auth_sessions(expires_at);

CREATE TABLE login_throttles (
    throttle_key VARCHAR(64) NOT NULL PRIMARY KEY,
    failure_count INT NOT NULL DEFAULT 0,
    locked_until BIGINT NULL,
    updated_at BIGINT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE login_logs (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NULL,
    attempted_identity VARCHAR(255) NOT NULL,
    success TINYINT NOT NULL DEFAULT 0,
    failure_reason VARCHAR(255) NULL,
    client_ip VARCHAR(64) NOT NULL DEFAULT '',
    user_agent VARCHAR(512) NOT NULL DEFAULT '',
    login_at BIGINT NOT NULL DEFAULT 0,
    logout_at BIGINT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX login_logs_login_at ON login_logs(login_at);
CREATE INDEX login_logs_user_id ON login_logs(user_id);

CREATE TABLE sys_config (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `key` VARCHAR(100) NOT NULL,
    value MEDIUMTEXT NOT NULL,
    type INT NOT NULL DEFAULT 1,
    created_at BIGINT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_at BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX sys_config_key ON sys_config(`key`);

CREATE TABLE teachers (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    avatar VARCHAR(512) NOT NULL DEFAULT '',
    status TINYINT NOT NULL DEFAULT 1,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX teachers_status ON teachers(status);

CREATE TABLE categories (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    parent_id BIGINT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    created_at BIGINT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_at BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE courses (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    short_description VARCHAR(500) NOT NULL DEFAULT '',
    category_id BIGINT NOT NULL DEFAULT 0,
    cover VARCHAR(512) NOT NULL DEFAULT '',
    price DECIMAL(12, 2) NOT NULL DEFAULT 0,
    duration DECIMAL(10, 2) NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 2,
    published_at BIGINT NOT NULL DEFAULT 0,
    description_image VARCHAR(512) NOT NULL DEFAULT '',
    course_type_code VARCHAR(100) NOT NULL DEFAULT '',
    created_at BIGINT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_at BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX courses_status ON courses(status);
CREATE INDEX courses_category_id ON courses(category_id);
CREATE INDEX courses_course_type_code ON courses(course_type_code);

CREATE TABLE course_teachers (
    course_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    PRIMARY KEY (course_id, teacher_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX course_teachers_teacher_id ON course_teachers(teacher_id);

CREATE TABLE course_chapters (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    course_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(2000) NOT NULL DEFAULT '',
    file VARCHAR(512) NOT NULL DEFAULT '',
    duration DECIMAL(10, 2) NOT NULL DEFAULT 0,
    teacher_id BIGINT NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX course_chapters_course_id ON course_chapters(course_id);

CREATE TABLE announcements (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content MEDIUMTEXT NOT NULL,
    status TINYINT NOT NULL DEFAULT 0,
    top TINYINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL DEFAULT 0,
    created_user BIGINT NULL,
    published_at BIGINT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX announcements_status_top_created
    ON announcements(status, top, created_at);

CREATE TABLE question_categories (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    parent_id BIGINT NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX question_categories_parent_id ON question_categories(parent_id);

CREATE TABLE questions (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    title TEXT NOT NULL,
    options VARCHAR(4000) NOT NULL DEFAULT '',
    answer VARCHAR(4000) NOT NULL DEFAULT '',
    status TINYINT NOT NULL DEFAULT 1,
    category_id BIGINT NOT NULL DEFAULT 0,
    parent_id BIGINT NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    score INT NOT NULL DEFAULT 1,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX questions_parent_id ON questions(parent_id);
CREATE INDEX questions_category_id ON questions(category_id);
CREATE INDEX questions_type_status_parent ON questions(type, status, parent_id);

CREATE TABLE exams (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    code VARCHAR(100) NOT NULL,
    exam_time BIGINT NOT NULL DEFAULT 0,
    duration INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    is_mock TINYINT NOT NULL DEFAULT 0,
    created_by BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX exams_code ON exams(code);
CREATE INDEX exams_is_mock ON exams(is_mock);

CREATE TABLE exam_sections (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    exam_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    sort_order INT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX exam_sections_exam_id ON exam_sections(exam_id);

CREATE TABLE exam_section_questions (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    exam_section_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX exam_section_questions_section_id
    ON exam_section_questions(exam_section_id);
CREATE INDEX exam_section_questions_question_id
    ON exam_section_questions(question_id);

CREATE TABLE exam_attempts (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    exam_id BIGINT NOT NULL,
    start_time BIGINT NOT NULL DEFAULT 0,
    end_time BIGINT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 0,
    submitted_at BIGINT NOT NULL DEFAULT 0,
    total_score INT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX exam_attempts_exam_id ON exam_attempts(exam_id);
CREATE INDEX exam_attempts_user_exam ON exam_attempts(user_id, exam_id);

CREATE TABLE exam_answers (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    attempt_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    answer VARCHAR(4000) NOT NULL DEFAULT '',
    is_correct TINYINT NOT NULL DEFAULT 0,
    score INT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX exam_answers_attempt_question
    ON exam_answers(attempt_id, question_id);

CREATE TABLE files (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(100) NOT NULL DEFAULT 'application/octet-stream',
    size BIGINT NOT NULL DEFAULT 0,
    md5 VARCHAR(32) NOT NULL DEFAULT '',
    status TINYINT NOT NULL DEFAULT 1,
    storage_path VARCHAR(512) NOT NULL,
    created_by BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX files_md5 ON files(md5);

CREATE TABLE learning_progress (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    course_id BIGINT NOT NULL,
    chapter_id BIGINT NOT NULL DEFAULT 0,
    user_id BIGINT NOT NULL,
    progress DECIMAL(7, 4) NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX learning_progress_user ON learning_progress(user_id);
CREATE INDEX learning_progress_course_user
    ON learning_progress(course_id, user_id);

CREATE TABLE course_notes (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    course_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    comment TEXT NOT NULL,
    created_time BIGINT NOT NULL DEFAULT 0,
    attachments TEXT NOT NULL,
    parent_id BIGINT NOT NULL DEFAULT 0,
    like_count INT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX course_notes_course ON course_notes(course_id, created_time);
CREATE INDEX course_notes_user ON course_notes(user_id);

CREATE TABLE note_likes (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    comment_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at BIGINT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX note_likes_comment ON note_likes(comment_id);
CREATE INDEX note_likes_user ON note_likes(user_id);

CREATE TABLE question_records (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    answer VARCHAR(4000) NOT NULL DEFAULT '',
    is_correct TINYINT NOT NULL DEFAULT 0,
    answered TINYINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX question_records_user_answered
    ON question_records(user_id, answered);
CREATE INDEX question_records_user_question
    ON question_records(user_id, question_id);
CREATE INDEX question_records_question ON question_records(question_id);

CREATE TABLE dictionary_types (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NOT NULL DEFAULT '',
    status TINYINT NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    built_in TINYINT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX dictionary_types_code ON dictionary_types(code);
CREATE INDEX dictionary_types_order ON dictionary_types(status, sort_order, id);

CREATE TABLE dictionary_items (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    type_id BIGINT NOT NULL,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NOT NULL DEFAULT '',
    status TINYINT NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    built_in TINYINT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX dictionary_items_type_code ON dictionary_items(type_id, code);
CREATE INDEX dictionary_items_type_order
    ON dictionary_items(type_id, status, sort_order, id);
