[login]
api_key = e0547f648c7c78cb46b2382ec267f4a10073e8a5bba7f1d9
; 多个user_id用逗号分隔，每个对应一个指纹浏览器
; 例如: user_id = id1,id2,id3,id4,id5
user_id = k1f2nilr
user_agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36 Edg/143.0.0.0
